import { Inter } from 'next/font/google';
import AppProviders from '@/components/providers/AppProviders';
import React from 'react';
import Header from '@/components/header/Header';
import '../styles/reset.css';
import InitialLoadingCover from '@/components/common/InitialLoadingCover';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <InitialLoadingCover>
            <>
              <Header />
              {children}
            </>
          </InitialLoadingCover>
        </AppProviders>
      </body>
    </html>
  );
}
