name: MyNewsVault CI Actions

on: 
  pull_request:
    branches: [develop]
jobs:
  ci-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout
      - name: set node-version
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: install dependencies
        run: npm ci

      - name: lint Check
        run: npm run lint

      - name: unit test
        run: npm run test