name: My News Valut Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # 우분투 ec2랑 맞추기
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
      # known_hosts에 EC2 호스트 추가
      # known_hosts에 EC2 호스트를 추가하여 SSH 연결 시 호스트 검증
      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        

      # 기존 디렉토리 날리고 git clone 수행
      - name: Clone repository to mnv dir
        run: |
          rm -rf /usr/share/nginx/my-news-vault
          git clone https://github.com/imnotpizza/my-news-vault.git /usr/share/nginx/my-news-vault


      # 빌드 및 배포
      # env 파일 생성 후 env 추가 커맨드 dd
      # webhook 될수있으면 추가
      - name: install, build and daemonize
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt-get update && sudo apt-get install -y yarn
          yarn -v
          cd /usr/share/nginx/my-news-vault
          yarn install --immutable
          yarn build
          pm2 start ecosystem.config.js
          pm2 startup
          EOF
