name: My News Valut Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # 우분투 ec2랑 맞추기
    # Ubuntu 24.04.2 LTS x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
      # known_hosts에 EC2 호스트 추가
      # known_hosts에 EC2 호스트를 추가하여 SSH 연결 시 호스트 검증
      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        

      # 기존 디렉토리 날리고 git clone 수행
      - name: Clone repository to mnv dir
        run: |
          rm -rf /usr/share/nginx/my-news-vault
          git clone https://github.com/imnotpizza/cicd-nextjs-sample.git /usr/share/nginx/my-news-vault


      # 빌드 및 배포
      # env 파일 생성 후 env 추가 커맨드 dd
      # webhook 될수있으면 추가
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            if [ -d "/usr/share/nginx/my-news-vault" ]; then
              cd /usr/share/nginx/my-news-vault
              git pull origin master
            else
              git clone https://github.com/imnotpizza/cicd-nextjs-sample.git /usr/share/nginx/my-news-vault
            fi

            # Yarn 설치
            sudo apt update
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt install -y yarn
            yarn --version

            # 의존성 설치 및 빌드
            cd /usr/share/nginx/my-news-vault
            yarn install --frozen-lockfile
            yarn build

            # .env 파일 루트에 생성
            echo "${{ secrets.ENV_PROD }}" > .env

            # PM2 설치 및 실행
            pm2 start ecosystem.config.js

            # Nginx 리로드
            sudo systemctl reload nginx
          EOF
